modLoader = "javafml"
loaderVersion = "[44,)"
license = "MIT"
issueTrackerURL="https://github.com/whizvox/Precision-Enchanter/issues"
[[mods]]
modId = "precisionenchanter"
version = "${file.jarVersion}"
displayName = "Precision Enchanter"
#updateJSONURL="http://myurl.me/"
displayURL="http://github.com/whizvox/Precision-Enchanter"
#logoFile="precisionenchanter.png"
#credits="Thanks for this example mod goes to Java"
authors = "whizvox"
description = '''
Have more control over enchanting! Remove the randomness by crafting and removing specific enchantments.
'''

[[dependencies.precisionenchanter]]
modId = "forge"
mandatory = true
versionRange = "[44,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.precisionenchanter]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.3,1.20)"
ordering = "NONE"
side = "BOTH"
